# Site settings
author: Wendy Hamilton
title: 
header-img: img/home-bg.png
email: wdhamilton117@gmail.com
copyright_name: Wendy Hamilton
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wendel117

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
